---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-service
  labels:
    app: prediction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-service
  template:
    metadata:
      labels:
        app: prediction-service
    spec:
      containers:
        - name: prediction-service
          image: jeffgorithm/prediction-service
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  type: LoadBalancer
  selector:
    app: prediction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80